site_name: Mindustry Wiki Indonesia
site_url: https://mindustryid.github.io/wiki/
repo_url: https://github.com/Mindustryid/wiki
docs_dir: 'docs_out'
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  custom_dir: overrides
  features:
    - navigation.tracking
extra_css:
  - 'stylesheets/style.css'
